### ISSUE TITLE
feat: switch commune page header to display links

### ISSUE THREAD

**Issue by EdSDR** [agicommies/commune-page#72]
![Image](https://github.com/agicommies/commune-page/assets/89485015/94d2d1ab-f177-4be6-8bb2-52641c6e04c3)

**Comment by steinerkelvin** [comment]
wdym?

**Comment by EdSDR** [comment]
> wdym?

i was talking to honza and vini and we decided that having only one button with box on the header was kinda wierd

**Comment by steinerkelvin** [comment]
Oh, I have a different view on this. Keep the button on the right. Move the links to the middle.

And limit the width because it's extra spacy on my screen  :v

Render on my screen:

![image](https://github.com/agicommies/commune-page/assets/2822370/b104366a-a181-42c9-ad2b-b1f64f1614f5)

How I would do:

![image](https://github.com/agicommies/commune-page/assets/2822370/d7a0714f-56b1-4679-ba0c-3a23e0565f27)
